<?php

declare(strict_types = 1);

use JetBrains\PhpStorm\ArrayShape;

/**
 * @file
 */


#[ArrayShape([
  'my-module-templatename' => "\null[][]"
])]
function mymodule_theme($existing, $type, $theme, $path): array
{
  return [
    'mymodule-templatename' => [
      'variables' => ['varname1' => null, 'varname2' => null],
      // Declare all variables that you want to be able to pass to this template
    ],
  ];
}
