<?php

declare(strict_types = 1);

use JetBrains\PhpStorm\ArrayShape;

/**
 * @file
 */


#[ArrayShape([
  'mymodule_templatename' => "\null[][]"
])]
function mymodule_theme($existing, $type, $theme, $path): array
{
  return [
    'mymodule_templatename' => [
      'variables' => ['varname1' => null, 'varname2' => null],
      // 'template'
      // Declare all variables that you want to be able to pass to this template
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
// function mymodule_preprocess_html(&$variables)
// {
//   $random_message = \Drupal::service('mymodule.random_message')->getRandomMessage();
//   \Drupal::messenger()->addMessage($random_message);
//   // drupal_set_message($random_message);
// }

/**
 * Implements hook_preprocess_HOOK().
 */
function mymodule_preprocess_html(&$variables) {
  \Drupal::service('mymodule.random_drupal_message')->setRandomMessage();
}
